### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by rqwa**
I split the previous pull request. This request contains all changes not linked to the grid feature

### CODE REVIEW

**Comment by cbourjau** [comment]
While being at it, could you please mention me (original author) in the readme, please? Thanks!

**Comment by rqwa** [comment]
Do you think the text about contributors should also be updated?

**Comment by mpuccio** [comment]
Hi @rqwa, yes: let's update the contributors section as well

**Comment by rqwa** [comment]
Is anything missing for merging this pull request?

**Pull request merged**
