### PR TITLE
Grid feature

### PR DESCRIPTION
**Pull request by rqwa**
Feature for controlling grid jobs with nittygriddy. See https://github.com/cbourjau/nittygriddy/issues/22
Currently only resubmission is possible. The option to kill all jobs will follow.
Please test if it works.

### CODE REVIEW

**Comment by mpuccio** [comment]
Nice! I will try it locally and I will let you know!

**Comment by mpuccio** [comment]
I found this very useful, just a minor fix if it is possible: if you run `nitty grid` in a proper folder it does not give you any output, I think it would be worth displaying the help in this cases.
In any case, if you prefer doing it in another PR I would be fine with merging this.

**Comment by rqwa** [comment]
I will add the notification to this pull request. I realised that two commits are general improvements. Should I move them to a another branch or is it fine to leave them in this pull request?

**Comment by mpuccio** [comment]
Fine with me to keep them in this PR. Thanks!

**Comment by rqwa** [comment]
There is now an error message if only `nitty grid` is run. I also implemented the detection non splitting jobs for resubmission as they are not listed with `gbbox ps -fs`. This primarily affects merging jobs.

**Comment by mpuccio** [comment]
Thanks a lot! This looks good to me! Meging.

**Pull request merged**
